// source: external_file.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

goog.exportSymbol('proto.mediapipe.tasks.core.proto.ExternalFile', null, global);
goog.exportSymbol('proto.mediapipe.tasks.core.proto.FileDescriptorMeta', null, global);
goog.exportSymbol('proto.mediapipe.tasks.core.proto.FilePointerMeta', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mediapipe.tasks.core.proto.ExternalFile = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mediapipe.tasks.core.proto.ExternalFile, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mediapipe.tasks.core.proto.ExternalFile.displayName = 'proto.mediapipe.tasks.core.proto.ExternalFile';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mediapipe.tasks.core.proto.FileDescriptorMeta = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mediapipe.tasks.core.proto.FileDescriptorMeta, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mediapipe.tasks.core.proto.FileDescriptorMeta.displayName = 'proto.mediapipe.tasks.core.proto.FileDescriptorMeta';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mediapipe.tasks.core.proto.FilePointerMeta = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mediapipe.tasks.core.proto.FilePointerMeta, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mediapipe.tasks.core.proto.FilePointerMeta.displayName = 'proto.mediapipe.tasks.core.proto.FilePointerMeta';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mediapipe.tasks.core.proto.ExternalFile.prototype.toObject = function(opt_includeInstance) {
  return proto.mediapipe.tasks.core.proto.ExternalFile.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mediapipe.tasks.core.proto.ExternalFile} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mediapipe.tasks.core.proto.ExternalFile.toObject = function(includeInstance, msg) {
  var f, obj = {
    fileContent: msg.getFileContent_asB64(),
    fileName: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    fileDescriptorMeta: (f = msg.getFileDescriptorMeta()) && proto.mediapipe.tasks.core.proto.FileDescriptorMeta.toObject(includeInstance, f),
    filePointerMeta: (f = msg.getFilePointerMeta()) && proto.mediapipe.tasks.core.proto.FilePointerMeta.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mediapipe.tasks.core.proto.ExternalFile}
 */
proto.mediapipe.tasks.core.proto.ExternalFile.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mediapipe.tasks.core.proto.ExternalFile;
  return proto.mediapipe.tasks.core.proto.ExternalFile.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mediapipe.tasks.core.proto.ExternalFile} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mediapipe.tasks.core.proto.ExternalFile}
 */
proto.mediapipe.tasks.core.proto.ExternalFile.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setFileContent(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setFileName(value);
      break;
    case 3:
      var value = new proto.mediapipe.tasks.core.proto.FileDescriptorMeta;
      reader.readMessage(value,proto.mediapipe.tasks.core.proto.FileDescriptorMeta.deserializeBinaryFromReader);
      msg.setFileDescriptorMeta(value);
      break;
    case 4:
      var value = new proto.mediapipe.tasks.core.proto.FilePointerMeta;
      reader.readMessage(value,proto.mediapipe.tasks.core.proto.FilePointerMeta.deserializeBinaryFromReader);
      msg.setFilePointerMeta(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mediapipe.tasks.core.proto.ExternalFile.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mediapipe.tasks.core.proto.ExternalFile.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mediapipe.tasks.core.proto.ExternalFile} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mediapipe.tasks.core.proto.ExternalFile.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getFileDescriptorMeta();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.mediapipe.tasks.core.proto.FileDescriptorMeta.serializeBinaryToWriter
    );
  }
  f = message.getFilePointerMeta();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.mediapipe.tasks.core.proto.FilePointerMeta.serializeBinaryToWriter
    );
  }
};


/**
 * optional bytes file_content = 1;
 * @return {!(string|Uint8Array)}
 */
proto.mediapipe.tasks.core.proto.ExternalFile.prototype.getFileContent = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes file_content = 1;
 * This is a type-conversion wrapper around `getFileContent()`
 * @return {string}
 */
proto.mediapipe.tasks.core.proto.ExternalFile.prototype.getFileContent_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getFileContent()));
};


/**
 * optional bytes file_content = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getFileContent()`
 * @return {!Uint8Array}
 */
proto.mediapipe.tasks.core.proto.ExternalFile.prototype.getFileContent_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getFileContent()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.mediapipe.tasks.core.proto.ExternalFile} returns this
 */
proto.mediapipe.tasks.core.proto.ExternalFile.prototype.setFileContent = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.mediapipe.tasks.core.proto.ExternalFile} returns this
 */
proto.mediapipe.tasks.core.proto.ExternalFile.prototype.clearFileContent = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mediapipe.tasks.core.proto.ExternalFile.prototype.hasFileContent = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string file_name = 2;
 * @return {string}
 */
proto.mediapipe.tasks.core.proto.ExternalFile.prototype.getFileName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.mediapipe.tasks.core.proto.ExternalFile} returns this
 */
proto.mediapipe.tasks.core.proto.ExternalFile.prototype.setFileName = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.mediapipe.tasks.core.proto.ExternalFile} returns this
 */
proto.mediapipe.tasks.core.proto.ExternalFile.prototype.clearFileName = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mediapipe.tasks.core.proto.ExternalFile.prototype.hasFileName = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional FileDescriptorMeta file_descriptor_meta = 3;
 * @return {?proto.mediapipe.tasks.core.proto.FileDescriptorMeta}
 */
proto.mediapipe.tasks.core.proto.ExternalFile.prototype.getFileDescriptorMeta = function() {
  return /** @type{?proto.mediapipe.tasks.core.proto.FileDescriptorMeta} */ (
    jspb.Message.getWrapperField(this, proto.mediapipe.tasks.core.proto.FileDescriptorMeta, 3));
};


/**
 * @param {?proto.mediapipe.tasks.core.proto.FileDescriptorMeta|undefined} value
 * @return {!proto.mediapipe.tasks.core.proto.ExternalFile} returns this
*/
proto.mediapipe.tasks.core.proto.ExternalFile.prototype.setFileDescriptorMeta = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mediapipe.tasks.core.proto.ExternalFile} returns this
 */
proto.mediapipe.tasks.core.proto.ExternalFile.prototype.clearFileDescriptorMeta = function() {
  return this.setFileDescriptorMeta(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mediapipe.tasks.core.proto.ExternalFile.prototype.hasFileDescriptorMeta = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional FilePointerMeta file_pointer_meta = 4;
 * @return {?proto.mediapipe.tasks.core.proto.FilePointerMeta}
 */
proto.mediapipe.tasks.core.proto.ExternalFile.prototype.getFilePointerMeta = function() {
  return /** @type{?proto.mediapipe.tasks.core.proto.FilePointerMeta} */ (
    jspb.Message.getWrapperField(this, proto.mediapipe.tasks.core.proto.FilePointerMeta, 4));
};


/**
 * @param {?proto.mediapipe.tasks.core.proto.FilePointerMeta|undefined} value
 * @return {!proto.mediapipe.tasks.core.proto.ExternalFile} returns this
*/
proto.mediapipe.tasks.core.proto.ExternalFile.prototype.setFilePointerMeta = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mediapipe.tasks.core.proto.ExternalFile} returns this
 */
proto.mediapipe.tasks.core.proto.ExternalFile.prototype.clearFilePointerMeta = function() {
  return this.setFilePointerMeta(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mediapipe.tasks.core.proto.ExternalFile.prototype.hasFilePointerMeta = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mediapipe.tasks.core.proto.FileDescriptorMeta.prototype.toObject = function(opt_includeInstance) {
  return proto.mediapipe.tasks.core.proto.FileDescriptorMeta.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mediapipe.tasks.core.proto.FileDescriptorMeta} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mediapipe.tasks.core.proto.FileDescriptorMeta.toObject = function(includeInstance, msg) {
  var f, obj = {
    fd: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    length: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    offset: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mediapipe.tasks.core.proto.FileDescriptorMeta}
 */
proto.mediapipe.tasks.core.proto.FileDescriptorMeta.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mediapipe.tasks.core.proto.FileDescriptorMeta;
  return proto.mediapipe.tasks.core.proto.FileDescriptorMeta.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mediapipe.tasks.core.proto.FileDescriptorMeta} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mediapipe.tasks.core.proto.FileDescriptorMeta}
 */
proto.mediapipe.tasks.core.proto.FileDescriptorMeta.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFd(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLength(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setOffset(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mediapipe.tasks.core.proto.FileDescriptorMeta.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mediapipe.tasks.core.proto.FileDescriptorMeta.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mediapipe.tasks.core.proto.FileDescriptorMeta} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mediapipe.tasks.core.proto.FileDescriptorMeta.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt64(
      3,
      f
    );
  }
};


/**
 * optional int32 fd = 1;
 * @return {number}
 */
proto.mediapipe.tasks.core.proto.FileDescriptorMeta.prototype.getFd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.mediapipe.tasks.core.proto.FileDescriptorMeta} returns this
 */
proto.mediapipe.tasks.core.proto.FileDescriptorMeta.prototype.setFd = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.mediapipe.tasks.core.proto.FileDescriptorMeta} returns this
 */
proto.mediapipe.tasks.core.proto.FileDescriptorMeta.prototype.clearFd = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mediapipe.tasks.core.proto.FileDescriptorMeta.prototype.hasFd = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int64 length = 2;
 * @return {number}
 */
proto.mediapipe.tasks.core.proto.FileDescriptorMeta.prototype.getLength = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.mediapipe.tasks.core.proto.FileDescriptorMeta} returns this
 */
proto.mediapipe.tasks.core.proto.FileDescriptorMeta.prototype.setLength = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.mediapipe.tasks.core.proto.FileDescriptorMeta} returns this
 */
proto.mediapipe.tasks.core.proto.FileDescriptorMeta.prototype.clearLength = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mediapipe.tasks.core.proto.FileDescriptorMeta.prototype.hasLength = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int64 offset = 3;
 * @return {number}
 */
proto.mediapipe.tasks.core.proto.FileDescriptorMeta.prototype.getOffset = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.mediapipe.tasks.core.proto.FileDescriptorMeta} returns this
 */
proto.mediapipe.tasks.core.proto.FileDescriptorMeta.prototype.setOffset = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.mediapipe.tasks.core.proto.FileDescriptorMeta} returns this
 */
proto.mediapipe.tasks.core.proto.FileDescriptorMeta.prototype.clearOffset = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mediapipe.tasks.core.proto.FileDescriptorMeta.prototype.hasOffset = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mediapipe.tasks.core.proto.FilePointerMeta.prototype.toObject = function(opt_includeInstance) {
  return proto.mediapipe.tasks.core.proto.FilePointerMeta.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mediapipe.tasks.core.proto.FilePointerMeta} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mediapipe.tasks.core.proto.FilePointerMeta.toObject = function(includeInstance, msg) {
  var f, obj = {
    pointer: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    length: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mediapipe.tasks.core.proto.FilePointerMeta}
 */
proto.mediapipe.tasks.core.proto.FilePointerMeta.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mediapipe.tasks.core.proto.FilePointerMeta;
  return proto.mediapipe.tasks.core.proto.FilePointerMeta.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mediapipe.tasks.core.proto.FilePointerMeta} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mediapipe.tasks.core.proto.FilePointerMeta}
 */
proto.mediapipe.tasks.core.proto.FilePointerMeta.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setPointer(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLength(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mediapipe.tasks.core.proto.FilePointerMeta.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mediapipe.tasks.core.proto.FilePointerMeta.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mediapipe.tasks.core.proto.FilePointerMeta} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mediapipe.tasks.core.proto.FilePointerMeta.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt64(
      2,
      f
    );
  }
};


/**
 * optional uint64 pointer = 1;
 * @return {number}
 */
proto.mediapipe.tasks.core.proto.FilePointerMeta.prototype.getPointer = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.mediapipe.tasks.core.proto.FilePointerMeta} returns this
 */
proto.mediapipe.tasks.core.proto.FilePointerMeta.prototype.setPointer = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.mediapipe.tasks.core.proto.FilePointerMeta} returns this
 */
proto.mediapipe.tasks.core.proto.FilePointerMeta.prototype.clearPointer = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mediapipe.tasks.core.proto.FilePointerMeta.prototype.hasPointer = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int64 length = 2;
 * @return {number}
 */
proto.mediapipe.tasks.core.proto.FilePointerMeta.prototype.getLength = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.mediapipe.tasks.core.proto.FilePointerMeta} returns this
 */
proto.mediapipe.tasks.core.proto.FilePointerMeta.prototype.setLength = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.mediapipe.tasks.core.proto.FilePointerMeta} returns this
 */
proto.mediapipe.tasks.core.proto.FilePointerMeta.prototype.clearLength = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mediapipe.tasks.core.proto.FilePointerMeta.prototype.hasLength = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.mediapipe.tasks.core.proto);
